version: '3.7'

services:
  targetdataapi:
    container_name: targetdataapi
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_HOST=mongoapitest
      - ELASTIC_HOST=http://elasticsearch:9200

    volumes:
      - .:/python-docker

    networks:
      network_bridge:
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      network_bridge:

  mongo:
    image: mongo
    container_name: mongoapitest
    restart: always
    ports:
      - 27017:27017
    networks:
      network_bridge:


networks:
  network_bridge:
      external:
        name: network_bridge